<?php
$addADatabase = new Form('addADatabase', array(
    'view' => 'Module:databases/control/settings/databases/add-a-database',
    'controller' => 'Module:databases/DatabasesForms',
    'function' => 'addADatabase',
    'submitButtonText' => 'Add Database',
    'style' => 'width: 600px;',
));

$addADatabaseSection = new FormSection('database', array(
    'description' => '
        <p>Adding a database to Project allows you to have multiple storage points for data. This function does not actually create a database for you, you must create the database, username, and password before adding the reference to it here.</p>
    ',
));

// Build the instance options
$instances = array();
foreach(Project::getInstances() as $instance) {
    $instances[] = array('label' => $instance['id'].' ('.$instance['host'].$instance['accessPath'].')', 'value' => $instance['id']);
}

$addADatabaseSection->addFormComponentArray(array(
    new FormComponentDropDown('databaseType', 'Database type:', array(
            array('label' => 'MySql', 'value' => 'MySql'),
        ), array(
            'validationOptions' => array('required'),
        )
    ),
    new FormComponentSingleLineText('databaseHost', 'Database host:', array(
        'validationOptions' => array('required'),
        'initialValue' => 'localhost',
    )),
    new FormComponentSingleLineText('databasePort', 'Database port:', array(
        'validationOptions' => array('required'),
        'initialValue' => '3306',
        'width' => 'short',
    )),
    new FormComponentSingleLineText('databaseName', 'Database name:', array(
        'validationOptions' => array('required'),
    )),
    new FormComponentSingleLineText('databaseUsername', 'Database username:', array(
        'validationOptions' => array('required'),
    )),
    new FormComponentSingleLineText('databasePassword', 'Database password:', array(
        'validationOptions' => array('required', 'password'),
        'type' => 'password',
    )),
    new FormComponentSingleLineText('modelPath', 'Model path:', array(
    )),
    new FormComponentMultipleChoice('globalContext', '', array(
            array('value' => 'Yes', 'label' => 'This database is the global context for all models', 'checked' => true)
        ),
        array(
            'tip' => '<p>The global context is the default database each model generated by the models module will use (if not explicitly set).</p>',
        )
    ),
    new FormComponentMultipleChoice('allInstances', '', array(
            array('value' => 'Yes', 'label' => 'This database is accessible by all instances', 'checked' => true)
        ),
        array(
        )
    ),
    new FormComponentMultipleChoice('instances', 'This database is only accessible by these instances:', $instances, array(
        'forceLabel' => true,
        'dependencyOptions' => array(
            'display' => 'hide',
            'dependentOn' => array('allInstances'),
            'jsFunction' => "!$('#allInstances-choice1').is(':checked');",
        ),
    )),
));

$addADatabase->addFormSection($addADatabaseSection);
?>