<?php

/**
 * Test class for DatabaseException.
 * Generated by PHPUnit on 2010-12-21 at 14:38:00.
 */
class DatabaseExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DatabaseException
     */
    protected $object;

    /**
     * @var string
     */
    protected $message;

    protected function setUp() {
        $this->message = 'This is a DatabaseException';
        $this->object = new DatabaseException($this->message);
    }

    protected function tearDown() {
        
    }

    public function testToString() {
        $this->assertEquals($this->object->getMessage(), $this->message);
    }

    public function testTryCatch() {
        $exceptionCaught = false;
        try {
            throw new DatabaseException('This is a test of the DatabaseException');
        }
        catch(DatabaseException $e) {
            $exceptionCaught = true;
        }
        $this->assertTrue($exceptionCaught);
    }
}
?>
